SimpleTypeNode.TypeName returns *PathExpressionNode
goccy/go-zetasql pull request #38
Opened 2023-12-11 14:27 UTC by kitagry

fix #37 

I think SimpleTypeNode.TypeName should return PathExpressionNode. https://github.com/goccy/go-zetasql/blob/main/internal/ccall/zetasql/parser/parse_tree_generated.h#L1183

2023-12-17 02:40 UTC, goccy requested changes
Please use `newPathExpressionNode(v)`

2023-12-17 03:53 UTC, kitagry commented
@goccy Thank you for the review! I fixed.

2023-12-18 08:05 UTC, goccy approved these changes

2023-12-18 08:05 UTC, merged

2023-12-18 08:05 UTC, goccy commented
Thank you for your contribution !! LGTM 👍